server {
    listen 9494;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Cache static assets
    location ~* \.(css|js|json|png|jpg|svg|ico)$ {
        expires 1h;
        add_header Cache-Control "public";
    }
}
